
name: "Continuous Integration"

on:
  pull_request:
  push:

jobs:
  grumphp:
    name: "GrumPHP"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP with PCOV"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v3"

      - name: "Run GrumPHP"
        run: "vendor/bin/grumphp run"
